config/routes.rb
Onrails::Application.routes.draw do
  devise_for :users

  root :to => 'static_pages#home'
  get "about" => "static_pages#about"
  get "gift" => "static_pages#gift"
  get "love" => "static_pages#love"

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		<%= link_to "Это приложение написано с любовью, так как все мое обучение Ruby проходит с мыслями о моей девочке", "#" %>
		by <%= link_to "Твоя вторая половинка", "#" %>
	</small>
</div>

app/views/layouts/_header.html.erb


<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <a class="brand" href="#">St. Valentine's Day</a>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
      	<ul class="nav">
	        <li><%= link_to "Home", root_path %></li>
			
		</ul>
		<ul class="nav pull-right">
	        <li><%= link_to "Login", "#" %></li>
		</ul>
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GamifyRussia</title>
   <%= stylesheet_link_tag    "application", :media => "all" %>
   <%= javascript_include_tag "application" %>
   <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |name, msg| %>
        <% content_tag(:div, msg, class: "asert alert-#{name}") %>
      <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<form class ="center hero-unit">
  <fieldset>
    <h3><legend>Несколько теплых слов этим замечательным утром.</legend></h3>
    <p> Маша, я влюбился в тебя с первого взгляда, при нашей самой первой встрече,
      хотя еще общаясь с тобой по скайпу у меня уже было какое-то предчувствие, поэтому узнав, что 
      ты поедешь в Пермь, я тоже туда поехал, а в процессе общения
      с тобой я понял, что мы с тобой родственные души и ты именно та девушка, которую я
      ждал, ты - девушка моей мечты.<br>
      Я хочу, чтобы эта влюбленность переросла в большую и светлую любовь.<br>
      Ты для меня самое дорогое, что есть на этом свете.<br>
      
<p>
  <%= link_to "Меньше слов, хочу подарок :-)", gift_path, class: "btn btn-primary btn-large" %>
</p>
  </fieldset>
</form>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
<h1>Доброе утро, моя девочка :-*</h1>

<p>
Сегодня необычный день - сегодня день всех влюбленных.<br>
Я хотел сказать тебе несколько теплых слов, таким необычным способом.<br>
Руби очень сопротевлялась, но я ее осилил...<br>
Для этого нажми кнопочку ниже :-) <br>
</p>
<div>
<p>
	<%= link_to "Нажми на кнопку", about_path, class: "btn btn-primary btn-large" %>
</p>
</div>
</div>